# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare deployment
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          echo "API key $API_KEY"
          echo "Client ID $CLIENT_ID"
          echo "Spreadsheet ID $SPREADSHEET_ID" 

          sed -i "s/{{API_KEY}}/$API_KEY/g" index.html
          sed -i "s/{{CLIENT_ID}}/$CLIENT_ID/g" index.html
          sed -i "s/{{SPREADSHEET_ID}}/$SPREADSHEET_ID/g" index.html

          cat index.html
          git rev-parse HEAD > sha.txt

          mkdir build
          cp index.html badger-pin.png sha.txt build/

      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
